"""initial schema

Revision ID: 7ffa54192841
Revises: 
Create Date: 2026-04-30 21:10:40.590954
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7ffa54192841'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assembly_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_device_serial_number', sa.String(), nullable=False),
    sa.Column('child_item_serial_number', sa.String(), nullable=False),
    sa.Column('child_barcode_value', sa.String(), nullable=False),
    sa.Column('component_type', sa.String(), nullable=False),
    sa.Column('installed_by', sa.String(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=False),
    sa.Column('workstation_id', sa.String(), nullable=True),
    sa.Column('scan_event_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assembly_links_child_barcode_value'), 'assembly_links', ['child_barcode_value'], unique=False)
    op.create_index(op.f('ix_assembly_links_child_item_serial_number'), 'assembly_links', ['child_item_serial_number'], unique=False)
    op.create_index(op.f('ix_assembly_links_parent_device_serial_number'), 'assembly_links', ['parent_device_serial_number'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('work_session_id', sa.String(), nullable=True),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.Column('workstation_id', sa.String(), nullable=True),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_work_session_id'), 'audit_events', ['work_session_id'], unique=False)
    op.create_table('barcode_labels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('barcode_value', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_serial_number', sa.String(), nullable=False),
    sa.Column('label_type', sa.String(), nullable=False),
    sa.Column('printed_by', sa.String(), nullable=True),
    sa.Column('printed_at', sa.DateTime(), nullable=False),
    sa.Column('print_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barcode_labels_barcode_value'), 'barcode_labels', ['barcode_value'], unique=True)
    op.create_index(op.f('ix_barcode_labels_entity_serial_number'), 'barcode_labels', ['entity_serial_number'], unique=False)
    op.create_table('device_components',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_serial_number', sa.String(), nullable=False),
    sa.Column('component_type', sa.String(), nullable=False),
    sa.Column('component_serial_number', sa.String(), nullable=True),
    sa.Column('component_part_number', sa.String(), nullable=True),
    sa.Column('component_revision', sa.String(), nullable=True),
    sa.Column('installed_by', sa.String(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_components_device_serial_number'), 'device_components', ['device_serial_number'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_serial_number', sa.String(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('hardware_version', sa.String(), nullable=True),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('bootloader_version', sa.String(), nullable=True),
    sa.Column('production_status', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_serial_number'), 'devices', ['device_serial_number'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('related_entity_type', sa.String(), nullable=False),
    sa.Column('related_entity_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_test_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('test_run_id', sa.String(), nullable=False),
    sa.Column('device_serial_number', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('bootloader_version', sa.String(), nullable=True),
    sa.Column('mcu_log_path', sa.String(), nullable=True),
    sa.Column('report_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_test_runs_device_serial_number'), 'final_test_runs', ['device_serial_number'], unique=False)
    op.create_index(op.f('ix_final_test_runs_test_run_id'), 'final_test_runs', ['test_run_id'], unique=True)
    op.create_table('machines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('machine_type', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_machine_id'), 'machines', ['machine_id'], unique=True)
    op.create_table('nonconformities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ncr_id', sa.String(), nullable=False),
    sa.Column('device_serial_number', sa.String(), nullable=True),
    sa.Column('component_serial_number', sa.String(), nullable=True),
    sa.Column('process_stage', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detected_by', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nonconformities_device_serial_number'), 'nonconformities', ['device_serial_number'], unique=False)
    op.create_index(op.f('ix_nonconformities_ncr_id'), 'nonconformities', ['ncr_id'], unique=True)
    op.create_table('operators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('rfid_uid_hash', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfid_uid_hash')
    )
    op.create_index(op.f('ix_operators_operator_id'), 'operators', ['operator_id'], unique=True)
    op.create_table('production_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_serial_number', sa.String(), nullable=False),
    sa.Column('barcode_value', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=True),
    sa.Column('revision', sa.String(), nullable=True),
    sa.Column('drawing_number', sa.String(), nullable=True),
    sa.Column('drawing_revision', sa.String(), nullable=True),
    sa.Column('production_order', sa.String(), nullable=True),
    sa.Column('material_batch', sa.String(), nullable=True),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('created_by_operator_id', sa.String(), nullable=True),
    sa.Column('produced_at', sa.DateTime(), nullable=True),
    sa.Column('current_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_items_barcode_value'), 'production_items', ['barcode_value'], unique=True)
    op.create_index(op.f('ix_production_items_item_serial_number'), 'production_items', ['item_serial_number'], unique=True)
    op.create_table('qc_checklists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('checklist_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('process_stage', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_checklists_checklist_code'), 'qc_checklists', ['checklist_code'], unique=True)
    op.create_table('scan_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_event_id', sa.String(), nullable=False),
    sa.Column('barcode_value', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.Column('workstation_id', sa.String(), nullable=True),
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_events_barcode_value'), 'scan_events', ['barcode_value'], unique=False)
    op.create_index(op.f('ix_scan_events_scan_event_id'), 'scan_events', ['scan_event_id'], unique=True)
    op.create_table('service_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('device_serial_number', sa.String(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('technician_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('bootloader_version', sa.String(), nullable=True),
    sa.Column('package_path', sa.String(), nullable=True),
    sa.Column('package_hash', sa.String(), nullable=True),
    sa.Column('upload_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_sessions_device_serial_number'), 'service_sessions', ['device_serial_number'], unique=False)
    op.create_index(op.f('ix_service_sessions_session_id'), 'service_sessions', ['session_id'], unique=True)
    op.create_table('work_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('work_session_id', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('workstation_id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('rfid_uid_hash', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_sessions_operator_id'), 'work_sessions', ['operator_id'], unique=False)
    op.create_index(op.f('ix_work_sessions_work_session_id'), 'work_sessions', ['work_session_id'], unique=True)
    op.create_index(op.f('ix_work_sessions_workstation_id'), 'work_sessions', ['workstation_id'], unique=False)
    op.create_table('workstations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workstation_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('station_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workstations_workstation_id'), 'workstations', ['workstation_id'], unique=True)
    op.create_table('qc_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('device_serial_number', sa.String(), nullable=False),
    sa.Column('checklist_id', sa.String(), nullable=True),
    sa.Column('process_stage', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['qc_checklists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_runs_device_serial_number'), 'qc_runs', ['device_serial_number'], unique=False)
    op.create_index(op.f('ix_qc_runs_run_id'), 'qc_runs', ['run_id'], unique=True)
    op.create_table('qc_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('checklist_id', sa.String(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('requires_photo', sa.Boolean(), nullable=False),
    sa.Column('requires_measurement', sa.Boolean(), nullable=False),
    sa.Column('blocking_on_fail', sa.Boolean(), nullable=False),
    sa.Column('expected_value', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('tolerance_min', sa.Numeric(), nullable=True),
    sa.Column('tolerance_max', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['qc_checklists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qc_step_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('qc_run_id', sa.String(), nullable=False),
    sa.Column('step_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('measurement_value', sa.Numeric(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('mcu_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['qc_run_id'], ['qc_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qc_step_results')
    op.drop_table('qc_steps')
    op.drop_index(op.f('ix_qc_runs_run_id'), table_name='qc_runs')
    op.drop_index(op.f('ix_qc_runs_device_serial_number'), table_name='qc_runs')
    op.drop_table('qc_runs')
    op.drop_index(op.f('ix_workstations_workstation_id'), table_name='workstations')
    op.drop_table('workstations')
    op.drop_index(op.f('ix_work_sessions_workstation_id'), table_name='work_sessions')
    op.drop_index(op.f('ix_work_sessions_work_session_id'), table_name='work_sessions')
    op.drop_index(op.f('ix_work_sessions_operator_id'), table_name='work_sessions')
    op.drop_table('work_sessions')
    op.drop_index(op.f('ix_service_sessions_session_id'), table_name='service_sessions')
    op.drop_index(op.f('ix_service_sessions_device_serial_number'), table_name='service_sessions')
    op.drop_table('service_sessions')
    op.drop_index(op.f('ix_scan_events_scan_event_id'), table_name='scan_events')
    op.drop_index(op.f('ix_scan_events_barcode_value'), table_name='scan_events')
    op.drop_table('scan_events')
    op.drop_index(op.f('ix_qc_checklists_checklist_code'), table_name='qc_checklists')
    op.drop_table('qc_checklists')
    op.drop_index(op.f('ix_production_items_item_serial_number'), table_name='production_items')
    op.drop_index(op.f('ix_production_items_barcode_value'), table_name='production_items')
    op.drop_table('production_items')
    op.drop_index(op.f('ix_operators_operator_id'), table_name='operators')
    op.drop_table('operators')
    op.drop_index(op.f('ix_nonconformities_ncr_id'), table_name='nonconformities')
    op.drop_index(op.f('ix_nonconformities_device_serial_number'), table_name='nonconformities')
    op.drop_table('nonconformities')
    op.drop_index(op.f('ix_machines_machine_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_final_test_runs_test_run_id'), table_name='final_test_runs')
    op.drop_index(op.f('ix_final_test_runs_device_serial_number'), table_name='final_test_runs')
    op.drop_table('final_test_runs')
    op.drop_table('files')
    op.drop_index(op.f('ix_devices_device_serial_number'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_device_components_device_serial_number'), table_name='device_components')
    op.drop_table('device_components')
    op.drop_index(op.f('ix_barcode_labels_entity_serial_number'), table_name='barcode_labels')
    op.drop_index(op.f('ix_barcode_labels_barcode_value'), table_name='barcode_labels')
    op.drop_table('barcode_labels')
    op.drop_index(op.f('ix_audit_events_work_session_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_assembly_links_parent_device_serial_number'), table_name='assembly_links')
    op.drop_index(op.f('ix_assembly_links_child_item_serial_number'), table_name='assembly_links')
    op.drop_index(op.f('ix_assembly_links_child_barcode_value'), table_name='assembly_links')
    op.drop_table('assembly_links')
    # ### end Alembic commands ###

