"""expand qc run targets

Revision ID: 9bfe77cf8306
Revises: 7ffa54192841
Create Date: 2026-04-30 21:21:44.116413
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9bfe77cf8306'
down_revision = '7ffa54192841'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qc_runs', sa.Column('item_serial_number', sa.String(), nullable=True))
    op.add_column('qc_runs', sa.Column('barcode_value', sa.String(), nullable=True))
    op.create_index(op.f('ix_qc_runs_barcode_value'), 'qc_runs', ['barcode_value'], unique=False)
    op.create_index(op.f('ix_qc_runs_item_serial_number'), 'qc_runs', ['item_serial_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qc_runs_item_serial_number'), table_name='qc_runs')
    op.drop_index(op.f('ix_qc_runs_barcode_value'), table_name='qc_runs')
    op.drop_column('qc_runs', 'barcode_value')
    op.drop_column('qc_runs', 'item_serial_number')
    # ### end Alembic commands ###

